app = "pulse-mvp"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[checks]]
  type = "http"
  name = "web"
  interval = "5s"
  timeout = "2s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"


