app = "pulse-mvp"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "5s"
    interval     = "10s"
    timeout      = "2s"
    method       = "GET"
    path         = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"


