apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: europe-west1-docker.pkg.dev/serverless-runtimes/google-22/run/universal:public-image-next
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 23042ecc-780e-4743-bc67-b052540414b3
    run.googleapis.com/build-image-uri: europe-west1-docker.pkg.dev/pulse-adc8d/cloud-run-source-deploy/pulse-ingest
    run.googleapis.com/build-name: projects/394046395219/locations/europe-west1/builds/23042ecc-780e-4743-bc67-b052540414b3
    run.googleapis.com/build-source-location: gs://run-sources-pulse-adc8d-europe-west1/services/pulse-ingest/1758708369.679799-9a45c615fba6477790d9221683a1f847.zip#1758708379248194
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://pulse-ingest-394046395219.europe-west1.run.app","https://pulse-ingest-25kmv4khyq-ew.a.run.app"]'
  labels:
    cloud.googleapis.com/location: europe-west1
  name: pulse-ingest
  namespace: '394046395219'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 539.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: ouhyjssgpk
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers: 
      - env:
        - name: JOBS_ENABLED
          value: '1'
        - name: ALLOW_PROD_INGEST
          value: '1'
        - name: INGEST_SOURCES
          value: prnewswire
        - name: LOG_LEVEL
          value: info
        image: europe-west1-docker.pkg.dev/pulse-adc8d/cloud-run-source-deploy/pulse-ingest@sha256:2047e9ca25cdd674e8122e8cc6ee0c34c17d31b2c5a5711c88b093da1bfc613e
        name: pulse-ingest-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 394046395219-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
