name: CI Smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  frontend-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm -r install
      - name: Frontend diagnostic build
        run: pnpm -C frontend run build:diag
